# --- CONEXIUNE AZURE SQL ---
server.port=8082
spring.datasource.url=jdbc:sqlserver://sqlserver-studenti-gl.database.windows.net:1433;database=BD_Dealer-Auto_Gogonea_Luca_331AB;encrypt=true;trustServerCertificate=true;loginTimeout=30;

spring.datasource.username=CloudSAc68da1ac

spring.datasource.password=aici.e.parola.mea.reala.din.azure
spring.jpa.hibernate.ddl-auto=none

# 4. Afisare SQL in consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
spring.messages.encoding=UTF-8